### ISSUE TITLE
Case Sensitive Paths Error

### ISSUE THREAD

**Issue by ETNOL** [markitondemand/mk-ui#21]
Found an error occurs on my webpack build due to some case sensitive paths. Easy fix just to make sure all references within the code to other files match the exact file case.

Error in ./~/mk-ui/dist/js/autocomplete.js
Module not found: [CaseSensitivePathsPlugin] `c:\Projects\myProject\node_modules\mk-ui\Selectmenu.js` does not match the corresponding path on disk `selectmenu.js`.

 @ ./~/mk-ui/dist/js/autocomplete.js 141:2-143:4

**Comment by micha3ldavid** [comment]
Wait, so what is your proposed solution?
